### ISSUE TITLE
old slf4j pulled by jdeb breaks sbt-web asset pipeline 

### ISSUE THREAD

**Issue by guersam** [sbt/sbt-native-packager#291]
After upgrading sbt-native-packager 0.7.2 from 0.7.2-RC2 in a Play 2.3 project, I'm getting this error when running `assets`:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/guersam/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.5.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/guersam/.ivy2/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/guersam/.ivy2/cache/org.slf4j/slf4j-simple/jars/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: slf4j-api 1.6.x (or later) is incompatible with this binding.
SLF4J: Your binding is version 1.5.5 or earlier.
SLF4J: Upgrade your binding to version 1.6.x.
[trace] Stack trace suppressed: run last web-plugin:webJarsNodeModules for the full output.
[trace] Stack trace suppressed: run last web-assets:webJars for the full output.
[error] (web-plugin:webJarsNodeModules) java.lang.NoSuchMethodError: org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
[error] (web-assets:webJars) java.lang.ExceptionInInitializerError
```

It's caused by `org.vafer:jdeb:1.2` which depends on `org.apache.maven:maven-core:2.2.1`, bringing tons of `slf4j-api:1.5.x` for related libraries.

Is there any workaround to remove jdeb? I tried `addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "0.7.2" exclude ("org.vafer", "jdeb"))` but had no luck.
